import { analyzeTypeScript } from "../typescript"
import fs from "fs"
import { flatMap } from "../utils"

describe("integration-test", () => {
    test("bootstrap", async () => {
        const rootDir = "design-systems/bootstrap/repo/"
        const result = await analyzeTypeScript([`${rootDir}/types/index.d.ts`], `${rootDir}/types/tsconfig.json`)

        const componentNames = flatMap(result, file => file.components).map(comp => comp.name)

        expect(componentNames).toEqual([
            "Accordion",
            "AccordionCollapse",
            "AccordionToggle",
            "Badge",
            "Breadcrumb",
            "BreadcrumbItem",
            "Button",
            "ButtonGroup",
            "ButtonToolbar",
            "Card",
            "CardColumns",
            "CardDeck",
            "CardImg",
            "CardGroup",
            "Carousel",
            "CarouselItem",
            "CloseButton",
            "Col",
            "Collapse",
            "Dropdown",
            "DropdownButton",
            "Fade",
            "Form",
            "FormControl",
            "FormCheck",
            "FormGroup",
            "FormLabel",
            "FormText",
            "Container",
            "Image",
            "Figure",
            "InputGroup",
            "Jumbotron",
            "ListGroup",
            "ListGroupItem",
            "Media",
            "Modal",
            "ModalBody",
            "ModalDialog",
            "ModalFooter",
            "ModalTitle",
            "Nav",
            "Navbar",
            "NavbarBrand",
            "NavDropdown",
            "NavItem",
            "Overlay",
            "OverlayTrigger",
            "PageItem",
            "Pagination",
            "Popover",
            "ProgressBar",
            "ResponsiveEmbed",
            "Row",
            "SafeAnchor",
            "Spinner",
            "SplitButton",
            "Tab",
            "TabContainer",
            "TabContent",
            "Table",
            "TabPane",
            "Tabs",
            "ThemeProvider",
            "ToggleButton",
            "ToggleButtonGroup",
            "Tooltip",
        ])
    })
})
