import { analyzeTypeScript } from "../analyze"

describe("integration-test", () => {
    test("ant-design", async () => {
        const components = await analyzeTypeScript([`integration-test-data/antd/node_modules/antd/es/index.d.ts`])

        const componentNames = components.map(comp => comp.name)

        expect(componentNames).toEqual([
            "Affix",
            "Anchor",
            "AutoComplete",
            "Alert",
            "Avatar",
            "BackTop",
            "Badge",
            "Breadcrumb",
            "Button",
            "Calendar",
            "Card",
            "Collapse",
            "Carousel",
            "Cascader",
            "Checkbox",
            "Col",
            "Comment",
            "ConfigProvider",
            "Descriptions",
            "Divider",
            "Dropdown",
            "Drawer",
            "Form",
            "Icon",
            "Input",
            "InputNumber",
            "List",
            "LocaleProvider",
            "Menu",
            "Mentions",
            "Modal",
            "PageHeader",
            "Pagination",
            "Popconfirm",
            "Popover",
            "Progress",
            "Radio",
            "Rate",
            "Row",
            "Select",
            "Skeleton",
            "Slider",
            "Spin",
            "Steps",
            "Switch",
            "Table",
            "Transfer",
            "Tree",
            "TreeSelect",
            "Tabs",
            "Tag",
            "TimePicker",
            "Timeline",
            "Tooltip",
            "Mention",
            "Upload",
        ])
    })
})
