import { analyzeTypeScript } from "../analyze"

describe("integration-test", () => {
    test("blueprint", async () => {
        const components = await analyzeTypeScript([
            `integration-test-data/@blueprintjs/core/node_modules/@blueprintjs/core/lib/esm/index.d.ts`,
        ])

        const componentNames = components.map(comp => comp.name)

        expect(componentNames).toEqual([
            "AbstractComponent",
            "AbstractPureComponent",
            "Alert",
            "Breadcrumb",
            "Breadcrumbs",
            "Button",
            "AnchorButton",
            "ButtonGroup",
            "Callout",
            "Card",
            "Collapse",
            "CollapsibleList",
            "Dialog",
            "Divider",
            "Drawer",
            "EditableText",
            "ControlGroup",
            "Switch",
            "Radio",
            "Checkbox",
            "FileInput",
            "FormGroup",
            "InputGroup",
            "NumericInput",
            "RadioGroup",
            "TextArea",
            "H1",
            "H2",
            "H3",
            "H4",
            "H5",
            "H6",
            "Blockquote",
            "Code",
            "Pre",
            "Label",
            "OL",
            "UL",
            "HTMLSelect",
            "HTMLTable",
            "Hotkeys",
            "Icon",
            "Menu",
            "MenuDivider",
            "MenuItem",
            "Navbar",
            "NavbarDivider",
            "NavbarGroup",
            "NavbarHeading",
            "NonIdealState",
            "OverflowList",
            "Overlay",
            "Text",
            "PanelStack",
            "Popover",
            "Portal",
            "ProgressBar",
            "ResizeSensor",
            "MultiSlider",
            "RangeSlider",
            "Slider",
            "Spinner",
            "Tab",
            "Expander",
            "Tabs",
            "Tag",
            "TagInput",
            "Toast",
            "Toaster",
            "Tooltip",
            "Tree",
            "TreeNode",
        ])
    })
})
